/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import DAO.daoAseguradora;
import DAO.daoCDA;
import DAO.genericDAO;
import controlador.ctlAseguradora;
import controlador.ctlCDA;
import controlador.ctlLogin;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import modelo.Aseguradora;
import modelo.Departamento;
import modelo.Login;
import modelo.Municipio;
import modelo.Pais;

/**
 *
 * @author nicolasgarcia
 */
public class FrmAdmin extends javax.swing.JFrame {

    /**
     * Creates new form FrmAdmin
     */
    //controladores
    ctlAseguradora ctlAse;
    ctlLogin ctlLogin;
    ctlCDA ctlCDA;

    //DAOS
    daoCDA daoCDA;
    daoAseguradora daoAse;
    genericDAO genDAO;

    public FrmAdmin(Login admin) {
        initComponents();
        //Centra la interfaz grafica en la mitad de la pantalla
        setLocationRelativeTo(null);

        //controladores
        ctlAse = new ctlAseguradora();
        ctlLogin = new ctlLogin();
        ctlCDA = new ctlCDA();

        //daos
        daoAse = new daoAseguradora();
        daoCDA = new daoCDA();
        genDAO = new genericDAO();

        //cargar en combo box
        genDAO.cargarcb(cbPaisAse, "pais", "nombre");
        genDAO.cargarcb(cbPaisCda, "pais", "nombre");

        //cajas de textos, combobox y demas bloqueados
        txtUsuarioAse.setEnabled(false);
        txtUsuarioCda.setEnabled(false);
        btnModificarAse.setEnabled(false);
        btnEliminarCDA.setEnabled(false);
        btnModificarCDA.setEnabled(false);
        btnEliminarAse.setEnabled(false);

        //listar
        listarAseguradora();
        listarCDA();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtNitAse = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtRepreAse = new javax.swing.JTextField();
        txtNombreAse = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDireccionAse = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtFijoAse = new javax.swing.JTextField();
        txtCeluAse = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtCorreoAse = new javax.swing.JTextField();
        btnGuardarAse = new javax.swing.JButton();
        btnBuscarAse = new javax.swing.JButton();
        btnModificarAse = new javax.swing.JButton();
        btnEliminarAse = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableAseguradora = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        cbMuniAse = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        txtUsuarioAse = new javax.swing.JTextField();
        btnLimpiarAse = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        cbPaisAse = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        cbDeparAse = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFijoCda = new javax.swing.JTextField();
        txtNitCda = new javax.swing.JTextField();
        txtRepreCda = new javax.swing.JTextField();
        txtNombreCda = new javax.swing.JTextField();
        txtDireccionCda = new javax.swing.JTextField();
        txtCeluCda = new javax.swing.JTextField();
        btnGuardarCDA = new javax.swing.JButton();
        btnEliminarCDA = new javax.swing.JButton();
        btnBuscarCDA = new javax.swing.JButton();
        btnModificarCDA = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtCorreoCda = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCDA = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        cbMunicipioCda = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        txtUsuarioCda = new javax.swing.JTextField();
        btnLimpiarCDA = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        cbPaisCda = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        cbDeparCda = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        btnCerrarSession = new javax.swing.JButton();

        jTextField6.setText("jTextField6");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel8.setText("NIT:");

        jLabel9.setText("Representante legal:");

        jLabel10.setText("Nombre:");

        jLabel11.setText("Direccion:");

        jLabel12.setText("Telefono fijo:");

        txtFijoAse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFijoAseActionPerformed(evt);
            }
        });

        jLabel13.setText("Telefono movil:");

        jLabel14.setText("Correo:");

        btnGuardarAse.setText("Guardar");
        btnGuardarAse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarAseActionPerformed(evt);
            }
        });

        btnBuscarAse.setText("Buscar");
        btnBuscarAse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAseActionPerformed(evt);
            }
        });

        btnModificarAse.setText("Modificar");
        btnModificarAse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarAseActionPerformed(evt);
            }
        });

        btnEliminarAse.setText("Eliminar");
        btnEliminarAse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAseActionPerformed(evt);
            }
        });

        tableAseguradora.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tableAseguradora);

        jLabel15.setText("Municipio:");

        cbMuniAse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel17.setText("Usuario:");

        btnLimpiarAse.setText("Limpiar");
        btnLimpiarAse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarAseActionPerformed(evt);
            }
        });

        jLabel20.setText("Pais:");

        cbPaisAse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbPaisAse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPaisAseActionPerformed(evt);
            }
        });

        jLabel21.setText("Departamento:");

        cbDeparAse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbDeparAse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDeparAseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnGuardarAse)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscarAse)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnModificarAse)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminarAse))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDireccionAse, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNitAse, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRepreAse, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombreAse, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtFijoAse, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCeluAse, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel20)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel21)
                                        .addComponent(jLabel15))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtCorreoAse, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                        .addComponent(cbPaisAse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbDeparAse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbMuniAse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(btnLimpiarAse)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUsuarioAse, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12)
                    .addComponent(txtFijoAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNitAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13)
                    .addComponent(txtRepreAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCeluAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtNombreAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtCorreoAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txtDireccionAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbPaisAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbDeparAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMuniAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuarioAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarAse)
                    .addComponent(btnBuscarAse)
                    .addComponent(btnModificarAse)
                    .addComponent(btnEliminarAse)
                    .addComponent(btnLimpiarAse))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jTabbedPane1.addTab("Aseguradoras", jPanel1);

        jLabel1.setText("NIT:");

        jLabel2.setText("Representante legal:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Direccion:");

        jLabel5.setText("Telefono fijo:");

        jLabel6.setText("Telefono movil:");

        txtFijoCda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFijoCdaActionPerformed(evt);
            }
        });

        txtNitCda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNitCdaActionPerformed(evt);
            }
        });

        btnGuardarCDA.setText("Guardar");
        btnGuardarCDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCDAActionPerformed(evt);
            }
        });

        btnEliminarCDA.setText("Eliminar");
        btnEliminarCDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCDAActionPerformed(evt);
            }
        });

        btnBuscarCDA.setText("Buscar");
        btnBuscarCDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCDAActionPerformed(evt);
            }
        });

        btnModificarCDA.setText("Modificar");
        btnModificarCDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarCDAActionPerformed(evt);
            }
        });

        jLabel7.setText("Correo:");

        tableCDA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableCDA);

        jLabel16.setText("Municipio:");

        cbMunicipioCda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel18.setText("Usuario:");

        btnLimpiarCDA.setText("Limpiar");
        btnLimpiarCDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarCDAActionPerformed(evt);
            }
        });

        jLabel22.setText("Pais:");

        cbPaisCda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbPaisCda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPaisCdaActionPerformed(evt);
            }
        });

        jLabel23.setText("Departamento:");

        cbDeparCda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbDeparCda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDeparCdaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel23))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbMunicipioCda, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbDeparCda, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtNitCda, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRepreCda, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreCda, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtDireccionCda, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(186, 186, 186)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbPaisCda, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnGuardarCDA)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnBuscarCDA)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnModificarCDA)
                                        .addGap(24, 24, 24))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtUsuarioCda, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(btnEliminarCDA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLimpiarCDA))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCorreoCda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCeluCda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFijoCda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(16, 122, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(txtFijoCda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNitCda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(txtRepreCda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCeluCda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombreCda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtCorreoCda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(cbPaisCda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(cbDeparCda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbMunicipioCda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtDireccionCda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtUsuarioCda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarCDA)
                    .addComponent(btnBuscarCDA)
                    .addComponent(btnModificarCDA)
                    .addComponent(btnEliminarCDA)
                    .addComponent(btnLimpiarCDA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        jTabbedPane1.addTab("CDA", jPanel2);

        jLabel19.setFont(new java.awt.Font("Myriad Pro Light", 1, 36)); // NOI18N
        jLabel19.setText("Administrador");

        btnCerrarSession.setText("Cerrar Session");
        btnCerrarSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSessionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrarSession, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrarSession))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarCDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCDAActionPerformed
        try {
            //variables 
            //genera numero aleatorio para añadir al usuario
            int numero = (int) (Math.random() * 1000) + 1;
            //metodo que genera letras aleatorias para contraseña
            String letras = generarLetrasAleatorias();
            //variables 
            int nit = Integer.parseInt(txtNitCda.getText());
            String representante = txtRepreCda.getText();
            String nombre = txtNombreCda.getText();
            String direccion = txtDireccionCda.getText();
            String telefonoFijo = txtFijoCda.getText();
            String telefonoMovil = txtCeluCda.getText();
            String correo = txtCorreoCda.getText();
            String usuario = nombre + numero;
            String contraseña = letras + numero;
            String muni = (String) cbMunicipioCda.getSelectedItem();
            Municipio municipi = ctlAse.consulta(muni);
            int municipio = municipi.getId();
            //primero se guarda el usuario
            if (ctlLogin.SolicitudGuardar(usuario, contraseña, 2)) {
                //Despues de guardar usuario se guarda la aseguradora
                if (ctlCDA.SolicitudGuardar(nit, representante, nombre, direccion, telefonoFijo, telefonoMovil, correo, usuario, municipio)) {
                    JOptionPane.showMessageDialog(null, "CDA guardado exitosamente.");
                    limpiarCDA();
                    listarCDA();

                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar el CDA: " + e);

        }

    }//GEN-LAST:event_btnGuardarCDAActionPerformed

    private void btnBuscarCDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCDAActionPerformed
        try {
            int nit = Integer.parseInt(txtNitCda.getText());
            String[] datos = ctlCDA.SolicitudBuscar(nit);

            if (!datos[0].equals("")) {
                cargarInformacionCDA(datos);
           btnModificarCDA.setEnabled(true);
            btnEliminarCDA.setEnabled(true);
            } else {

                JOptionPane.showMessageDialog(this, "No se encuentra la aseguradora buscada");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error en la busqueda de la aseguradora: " + e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarCDAActionPerformed

    private void btnEliminarCDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCDAActionPerformed
        try {
            int nit = Integer.parseInt(txtNitCda.getText());

            if (ctlCDA.solicitudEliminar(nit)) {
                JOptionPane.showMessageDialog(this, "Aseguradora eliminada exitosamente");
                limpiarCDA();
                listarCDA();
            } else {
                JOptionPane.showMessageDialog(this, "Error al eliminar la aseguradora, rectifique e intente nuevamente");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar la aseguradora: " + e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarCDAActionPerformed

    private void btnGuardarAseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAseActionPerformed
        try {
            //variables 
            //genera numero aleatorio para añadir al usuario
            int numero = (int) (Math.random() * 1000) + 1;
            //metodo que genera letras aleatorias para contraseña
            String letras = generarLetrasAleatorias();
            //variables 
            int nit = Integer.parseInt(txtNitAse.getText());
            String representante = txtRepreAse.getText();
            String nombre = txtNombreAse.getText();
            String direccion = txtDireccionAse.getText();
            String telefonoFijo = txtFijoAse.getText();
            String telefonoMovil = txtCeluAse.getText();
            String correo = txtCorreoAse.getText();
            String usuario = nombre + numero;
            String contraseña = letras + numero;
            String muni = (String) cbMuniAse.getSelectedItem();
            Municipio municipi = ctlAse.consulta(muni);
            int municipio = municipi.getId();
            //primero se guarda el usuario
            if (ctlLogin.SolicitudGuardar(usuario, contraseña, 1)) {
                //Despues de guardar usuario se guarda la aseguradora
                if (ctlAse.SolicitudGuardar(nit, representante, nombre, direccion, telefonoFijo, telefonoMovil, correo, usuario, municipio)) {
                    JOptionPane.showMessageDialog(null, "Aseguradora guardado exitosamente.");
                    limpiarAseguradora();
                    listarAseguradora();

                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar la aseguradora: " + e);

        }
    }//GEN-LAST:event_btnGuardarAseActionPerformed

    private void btnBuscarAseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAseActionPerformed
        try {
            int nit = Integer.parseInt(txtNitAse.getText());
            String[] datos = ctlAse.SolicitudBuscar(nit);
            System.out.println(datos[0]);

            if (!datos[0].equals("")) {
                cargarInformacionAseguradora(datos);
            btnModificarAse.setEnabled(true);
            btnEliminarAse.setEnabled(true);
            } else {

                JOptionPane.showMessageDialog(this, "No se encuentra la aseguradora buscada");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error en la busqueda de la aseguradora: " + e);
        }
    }//GEN-LAST:event_btnBuscarAseActionPerformed

    private void btnEliminarAseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAseActionPerformed
        try {
            int nit = Integer.parseInt(txtNitAse.getText());

            if (ctlAse.solicitudEliminar(nit)) {
                JOptionPane.showMessageDialog(this, "Aseguradora eliminada exitosamente");
                limpiarAseguradora();
                listarAseguradora();
            } else {
                JOptionPane.showMessageDialog(this, "Error al eliminar la aseguradora, rectifique e intente nuevamente");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar la aseguradora: " + e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarAseActionPerformed

    private void txtNitCdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNitCdaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNitCdaActionPerformed

    private void txtFijoAseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFijoAseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFijoAseActionPerformed

    private void btnModificarAseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarAseActionPerformed
        try {
            //variables 

            //variables 
            int nit = Integer.parseInt(txtNitAse.getText());
            String representante = txtRepreAse.getText();
            String nombre = txtNombreAse.getText();
            String direccion = txtDireccionAse.getText();
            String telefonoFijo = txtFijoAse.getText();
            String telefonoMovil = txtCeluAse.getText();
            String correo = txtCorreoAse.getText();
            String usuario = txtUsuarioAse.getText();
            String muni = (String) cbMuniAse.getSelectedItem();
            Municipio municipi = ctlAse.consulta(muni);
            int municipio = municipi.getId();
            //Se modifica primero el usuario en la tabla usuario 

            if (ctlCDA.SolicitudModificar(nit, representante, nombre, direccion, telefonoFijo, telefonoMovil, correo, usuario, municipio)) {
                JOptionPane.showMessageDialog(null, "El CDA fue modificada exitosamente!");

            } else {
                JOptionPane.showMessageDialog(null, "No se pudo modificar el CDA, rectifique e intente nuevamente");

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al modificar CDA: " + e);

        }
    }//GEN-LAST:event_btnModificarAseActionPerformed

    private void txtFijoCdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFijoCdaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFijoCdaActionPerformed

    private void btnModificarCDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarCDAActionPerformed
        try {
            String usuario = txtUsuarioCda.getText();

            int nit = Integer.parseInt(txtNitCda.getText());
            String representante = txtRepreCda.getText();
            String nombre = txtNombreCda.getText();
            String direccion = txtDireccionCda.getText();
            String telefonoFijo = txtFijoCda.getText();
            String telefonoMovil = txtCeluCda.getText();
            String correo = txtCorreoCda.getText();
            String muni = (String) cbMunicipioCda.getSelectedItem();
            Municipio municipi = ctlAse.consulta(muni);
            int municipio = municipi.getId();
            //primero se guarda el usuario

            if (ctlCDA.SolicitudModificar(nit, representante, nombre, direccion, telefonoFijo, telefonoMovil, correo, usuario, municipio)) {
                JOptionPane.showMessageDialog(null, "CDA guardado exitosamente.");
                limpiarCDA();
                listarCDA();

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar el CDA: " + e);

        }


    }//GEN-LAST:event_btnModificarCDAActionPerformed

    private void btnLimpiarAseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarAseActionPerformed
        limpiarAseguradora();
    }//GEN-LAST:event_btnLimpiarAseActionPerformed

    private void btnLimpiarCDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarCDAActionPerformed

    }//GEN-LAST:event_btnLimpiarCDAActionPerformed

    private void cbPaisAseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPaisAseActionPerformed
        try {
            String nombre_pais = (String) cbPaisAse.getSelectedItem();
            Pais pais = daoAse.consultaPais(nombre_pais);
            int idPais = pais.getId();

            daoAse.listarEnComboDepartamentos(idPais);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al listar departamentos");
        }


    }//GEN-LAST:event_cbPaisAseActionPerformed

    private void cbDeparAseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDeparAseActionPerformed
        try {
            String nombre_depar = (String) cbDeparAse.getSelectedItem();
            Departamento depar = daoAse.consultaDepar(nombre_depar);
            int idDepar = depar.getId();

            daoAse.listarEnComboMunicipios(idDepar);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al listar municipios");
        }

    }//GEN-LAST:event_cbDeparAseActionPerformed

    private void cbPaisCdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPaisCdaActionPerformed
        try {
            String nombre_pais = (String) cbPaisCda.getSelectedItem();
            Pais pais = daoCDA.consultaPais(nombre_pais);
            int idPais = pais.getId();

            daoCDA.listarEnComboDepartamentos(idPais);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al listar departamentos");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPaisCdaActionPerformed

    private void cbDeparCdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDeparCdaActionPerformed
        try {
            String nombre_depar = (String) cbDeparCda.getSelectedItem();
            Departamento depar = daoCDA.consultaDepar(nombre_depar);
            int idDepar = depar.getId();

            daoCDA.listarEnComboMunicipios(idDepar);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al listar municipios");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cbDeparCdaActionPerformed

    private void btnCerrarSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSessionActionPerformed
        new FrmInicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSessionActionPerformed
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrmAdmin().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarAse;
    private javax.swing.JButton btnBuscarCDA;
    private javax.swing.JButton btnCerrarSession;
    private javax.swing.JButton btnEliminarAse;
    private javax.swing.JButton btnEliminarCDA;
    private javax.swing.JButton btnGuardarAse;
    private javax.swing.JButton btnGuardarCDA;
    private javax.swing.JButton btnLimpiarAse;
    private javax.swing.JButton btnLimpiarCDA;
    private javax.swing.JButton btnModificarAse;
    private javax.swing.JButton btnModificarCDA;
    public static javax.swing.JComboBox<String> cbDeparAse;
    public static javax.swing.JComboBox<String> cbDeparCda;
    public static javax.swing.JComboBox<String> cbMuniAse;
    public static javax.swing.JComboBox<String> cbMunicipioCda;
    private javax.swing.JComboBox<String> cbPaisAse;
    public static javax.swing.JComboBox<String> cbPaisCda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTable tableAseguradora;
    private javax.swing.JTable tableCDA;
    private javax.swing.JTextField txtCeluAse;
    private javax.swing.JTextField txtCeluCda;
    private javax.swing.JTextField txtCorreoAse;
    private javax.swing.JTextField txtCorreoCda;
    private javax.swing.JTextField txtDireccionAse;
    private javax.swing.JTextField txtDireccionCda;
    private javax.swing.JTextField txtFijoAse;
    private javax.swing.JTextField txtFijoCda;
    private javax.swing.JTextField txtNitAse;
    private javax.swing.JTextField txtNitCda;
    private javax.swing.JTextField txtNombreAse;
    private javax.swing.JTextField txtNombreCda;
    private javax.swing.JTextField txtRepreAse;
    private javax.swing.JTextField txtRepreCda;
    private javax.swing.JTextField txtUsuarioAse;
    private javax.swing.JTextField txtUsuarioCda;
    // End of variables declaration//GEN-END:variables
 //metodos para listar
    private void listarAseguradora() {
        tableAseguradora.setModel(ctlAse.SolicitudListar());
    }

    private void listarCDA() {
        tableCDA.setModel(ctlCDA.SolicitudListar());
    }
    //metodo para generar letras aleatorias

    private String generarLetrasAleatorias() {

        char[] letras = {'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'ñ', 'o', 'p', 'q', 'r', 's', 't', 'u',
            'u', 'v', 'w', 'x', 'y', 'z'};
        String pass;
        char[] conjunto = new char[8];
        //System.out.println(letras[(int) (Math.random() * (26) + 1)]);

        for (int i = 0; i < 8; i++) {
            // int el = (int) (Math.random() * 37);
            conjunto[i] = (char) letras[(int) (Math.random() * (26) + 1)];
        }
        return pass = new String(conjunto);

    }
//metodos para limpiar Campos

    private void limpiarAseguradora() {
        txtNitAse.setText("");
        txtRepreAse.setText("");
        txtNombreAse.setText("");
        txtDireccionAse.setText("");
        txtFijoAse.setText("");
        txtCeluAse.setText("");
        txtCorreoAse.setText("");
    }

    private void limpiarCDA() {
        txtNitCda.setText("");
        txtRepreCda.setText("");
        txtNombreCda.setText("");
        txtDireccionCda.setText("");
        txtFijoCda.setText("");
        txtCeluCda.setText("");
        txtCorreoCda.setText("");
    }
//metodos para cargar la informacion de las busquedas 

    private void cargarInformacionAseguradora(String[] datos) {
        txtNitAse.setText(datos[0]);
        txtRepreAse.setText(datos[1]);
        txtNombreAse.setText(datos[2]);
        txtDireccionAse.setText(datos[3]);
        txtFijoAse.setText(datos[4]);
        txtCeluAse.setText(datos[5]);
        txtCorreoAse.setText(datos[6]);
        txtUsuarioAse.setText(datos[7]);
    }

    private void cargarInformacionCDA(String[] datos) {
        txtNitCda.setText(datos[0]);
        txtRepreCda.setText(datos[1]);
        txtNombreCda.setText(datos[2]);
        txtDireccionCda.setText(datos[3]);
        txtFijoCda.setText(datos[4]);
        txtCeluCda.setText(datos[5]);
        txtCorreoCda.setText(datos[6]);
        txtUsuarioCda.setText(datos[7]);
    }

}
