/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import DAO.consultasDAO;
import DAO.daoAseguradora;
import DAO.daoCDA;
import DAO.daoLicencia;
import DAO.genericDAO;
import controlador.ctlAseguradora;
import controlador.ctlComparendo;
import controlador.ctlComparendoUsuario;
import controlador.ctlLicenciaCategoria;
import controlador.ctlLicenciaConduccion;
import controlador.ctlPropietario;
import controlador.ctlVehiculo;
import controladorReportes.CtlReporte;
import java.text.DateFormat;
import javax.swing.JOptionPane;
import modelo.ClaseVehiculo;
import modelo.Color;
import modelo.Departamento;
import modelo.EstadoV;
import modelo.Login;
import modelo.Marca;
import modelo.ModeloVehiculo;
import modelo.Municipio;
import modelo.Pais;
import modelo.Propieatario;
import modelo.TipoCombustible;
import modelo.TipoInfraccion;
import modelo.TipoServicio;

/**
 *
 * @author nicolasgarcia
 */
public class FrmConsecionario extends javax.swing.JFrame {

    /**
     * Creates new form FrmVehiculos
     */
    genericDAO genDAO;
    consultasDAO conDAO;
    daoCDA cdaDAO;
    daoAseguradora daoAse;
     
    CtlReporte ctlReporte;
    ctlVehiculo ctlVehiculo;
    ctlLicenciaConduccion ctlLicencia;
    ctlLicenciaCategoria ctlCategoria;
    ctlPropietario ctlPro;
    ctlComparendo ctlComp;
    ctlComparendoUsuario ctlCompUs;
    ctlAseguradora ctlAse;

    DateFormat variableFecha = DateFormat.getDateInstance();
    DateFormat variableFecha2 = DateFormat.getDateInstance();
    DateFormat variableFecha3 = DateFormat.getDateInstance();

    public FrmConsecionario(Login conceLog) {
        initComponents();
        setLocationRelativeTo(null);
        genDAO = new genericDAO();
        conDAO = new consultasDAO();
        cdaDAO = new daoCDA();
        daoAse = new daoAseguradora();

        ctlVehiculo = new ctlVehiculo();
        ctlLicencia = new ctlLicenciaConduccion();
        ctlCategoria = new ctlLicenciaCategoria();
        ctlPro = new ctlPropietario();
        ctlComp = new ctlComparendo();
        ctlCompUs = new ctlComparendoUsuario();
        ctlAse = new ctlAseguradora();
        ctlReporte = new CtlReporte();

        //Cargas en combobox
        genDAO.cargarcb(cbTipoInfraccion, "tipo_infraccion", "nombre");
        genDAO.cargarcb(cbPaisComparendo, "pais", "nombre");
        genDAO.cargarcb(cbTipoServicio, "tipo_servicio", "nombre");
        genDAO.cargarcb(cbClase, "clase_vehiculo", "nombre");
        genDAO.cargarcb(cbEstado, "estado_vehiculo", "nombre");
        genDAO.cargarcb(cbModelo, "modelo", "nombre");
        genDAO.cargarcb(cbColor, "color", "nombre");
        genDAO.cargarcb(cbMarca, "marca", "nombre");
        genDAO.cargarcb(cbTipoCombustible, "tipo_combustible", "nombre");
        conDAO.listarEnComboNumeroPoliza(cbNumeroPoliza, "seguro", "estado");
        genDAO.cargarcb(cbCategoria, "categorias_licencia", "categoria");
        ChooserDocLic.setEnabled(false);

        //cargar en lista
        listarComparendo();
        listarVehiculos();
        listarLicencias();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtNumeroLicencia = new javax.swing.JTextField();
        txtRestricciones = new javax.swing.JTextField();
        txtOrganismoEx = new javax.swing.JTextField();
        txtNumeroCiudadano = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        cbCategoria = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLicenciaConse = new javax.swing.JTable();
        ChooserDocExpLic = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        txtVehiculoTraspaso = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtCedulaTraspaso = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtPropietario = new javax.swing.JTextField();
        cbModelo = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        cbMarca = new javax.swing.JComboBox<>();
        cbColor = new javax.swing.JComboBox<>();
        cbTipoCombustible = new javax.swing.JComboBox<>();
        cbTipoServicio = new javax.swing.JComboBox<>();
        cbClase = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbEstado = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cbNumeroPoliza = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        txtLicenciaT = new javax.swing.JTextField();
        txtNumeroChasis = new javax.swing.JTextField();
        txtCilindraje = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNumeroPasajeros = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVehiculoConse = new javax.swing.JTable();
        ChooserDocMatricula = new com.toedter.calendar.JDateChooser();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        cbPaisComparendo = new javax.swing.JComboBox<>();
        cbDeparComparendo = new javax.swing.JComboBox<>();
        cbMunicipioComparendo = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtNumComparendo = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        cbTipoInfraccion = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        txtHoraComparendo = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txtLicenciaConComparendo = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        btnRegistrarComparendo = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblComparendoConse = new javax.swing.JTable();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        txtCedulaCiuComp = new javax.swing.JTextField();
        btnAsignarCuiComparendo = new javax.swing.JButton();
        ChooserDocFechaComparendo = new com.toedter.calendar.JDateChooser();
        jPanel7 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblFiltrarVehiculos = new javax.swing.JTable();
        bFiltrarVehiculo = new javax.swing.JButton();
        bFiltrarVehiculoTodo = new javax.swing.JButton();
        cbConsultasVehiculo = new javax.swing.JComboBox<>();
        tfFiltroVehiculo = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblFiltrarLicencia = new javax.swing.JTable();
        bFiltraLicenciaTodos = new javax.swing.JButton();
        bFiltrarLicencia = new javax.swing.JButton();
        tfFiltroLicencia = new javax.swing.JTextField();
        cbConsultasLicencia = new javax.swing.JComboBox<>();
        jLabel42 = new javax.swing.JLabel();
        ChooserDocLic = new com.toedter.calendar.JDateChooser();
        jPanel10 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        bFiltraComparendosTodos = new javax.swing.JButton();
        bFiltrarComparendo = new javax.swing.JButton();
        tfFiltroComparendo = new javax.swing.JTextField();
        cbConsultasComparendo = new javax.swing.JComboBox<>();
        jLabel43 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblFiltrarComparendo = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        btnCerrarSession = new javax.swing.JButton();
        ChooserDocExpLic2 = new com.toedter.calendar.JDateChooser();

        jLabel9.setText("Numero-chasis:");

        jLabel15.setText("Numero-chasis:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel19.setText("Numero-licencia:");

        jLabel20.setText("Fecha-expedicion:");

        jLabel21.setText("Restricciones:");

        jLabel22.setText("Organismo-expedidor:");

        jLabel23.setText("Numero-identidad-ciudadano:");

        txtRestricciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRestriccionesActionPerformed(evt);
            }
        });

        jButton2.setText("Registrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel25.setText("Categoria:");

        cbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tblLicenciaConse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblLicenciaConse);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtNumeroLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtRestricciones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChooserDocExpLic, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtOrganismoEx)
                            .addComponent(txtNumeroCiudadano)
                            .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(jButton2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(349, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(txtNumeroLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ChooserDocExpLic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(txtRestricciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(txtOrganismoEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(txtNumeroCiudadano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Licencia", jPanel2);

        jLabel26.setText("Ingrese la placa del vehiculo al cual le desea realizar el traspaso:");

        jLabel27.setText("Ingrese la cedula del ciudadano que sera el nuevo propietario del vehiculo:");

        txtCedulaTraspaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaTraspasoActionPerformed(evt);
            }
        });

        jButton3.setText("Traspasar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel26))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtVehiculoTraspaso)
                            .addComponent(txtCedulaTraspaso, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jButton3)))
                .addContainerGap(615, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtVehiculoTraspaso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtCedulaTraspaso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jButton3)
                .addContainerGap(676, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Traspasos", jPanel3);

        cbModelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel16.setText("Marca:");

        cbMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMarcaActionPerformed(evt);
            }
        });

        cbColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbTipoCombustible.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbTipoServicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbClase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel18.setText("Numero-poliza:");

        jLabel10.setText("Cilindraje:");

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel11.setText("Tipo-combustible:");

        cbNumeroPoliza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel12.setText("Fecha-matricula:");

        jLabel13.setText("Numero-pasajeros:");

        jLabel14.setText("Propietario:");

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel17.setText("VEHICULOS");

        jLabel1.setText("Placa:");

        jLabel2.setText("Licencia-transito:");

        jLabel3.setText("Tipo-servicio:");

        jLabel4.setText("Clase:");

        jLabel5.setText("Estado:");

        jLabel6.setText("Modelo:");

        jLabel7.setText("Color:");

        jLabel8.setText("Numero-chasis:");

        tblVehiculoConse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblVehiculoConse);

        jButton4.setText("Generar Reporte");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel16))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLicenciaT, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbModelo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbMarca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbTipoServicio, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbEstado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbClase, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel12))
                        .addComponent(jLabel11))
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtCilindraje)
                        .addComponent(txtNumeroChasis)
                        .addComponent(txtNumeroPasajeros)
                        .addComponent(txtPropietario)
                        .addComponent(cbColor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbTipoCombustible, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbNumeroPoliza, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ChooserDocMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(jLabel17))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jButton1)
                        .addGap(92, 92, 92)
                        .addComponent(jButton4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(398, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtLicenciaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cbColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtNumeroChasis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbTipoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(cbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cbModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtCilindraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(cbTipoCombustible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(jLabel5))
                            .addComponent(ChooserDocMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtNumeroPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(cbNumeroPoliza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Vehiculo", jPanel1);

        cbPaisComparendo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbPaisComparendo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPaisComparendoActionPerformed(evt);
            }
        });

        cbDeparComparendo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbDeparComparendo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDeparComparendoActionPerformed(evt);
            }
        });

        cbMunicipioComparendo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbMunicipioComparendo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMunicipioComparendoActionPerformed(evt);
            }
        });

        jLabel28.setText("Municipio:");

        jLabel29.setText("Departamento:");

        jLabel30.setText("Pais:");

        jLabel31.setText("Numero del Comparendo:");

        jLabel32.setText("Tipo Infraccion");

        cbTipoInfraccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel34.setText("Fecha:");

        txtHoraComparendo.setToolTipText("");

        jLabel35.setText("Hora:");

        jLabel37.setText("(hora : minutos)");

        txtLicenciaConComparendo.setToolTipText("");

        jLabel39.setText("Licencia De Conduccion:");

        btnRegistrarComparendo.setText("Registrar");
        btnRegistrarComparendo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarComparendoActionPerformed(evt);
            }
        });

        tblComparendoConse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblComparendoConse);

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel40.setText("Asignar Comparendo a  Ciudadano");

        jLabel41.setText("Cedula:");

        btnAsignarCuiComparendo.setText("Asignar");
        btnAsignarCuiComparendo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarCuiComparendoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel28)
                                .addComponent(jLabel29))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cbMunicipioComparendo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbDeparComparendo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addComponent(jLabel30)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cbPaisComparendo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(btnRegistrarComparendo)))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel31)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNumComparendo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addComponent(jLabel32)
                            .addGap(18, 18, 18)
                            .addComponent(cbTipoInfraccion, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 450, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addGap(18, 18, 18)
                                .addComponent(ChooserDocFechaComparendo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHoraComparendo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel37)))
                        .addGap(147, 147, 147))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(jLabel39)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLicenciaConComparendo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel41)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCedulaCiuComp, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(btnAsignarCuiComparendo)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(jLabel40)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(420, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel41)
                            .addComponent(txtCedulaCiuComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAsignarCuiComparendo))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel32)
                                    .addComponent(cbTipoInfraccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(ChooserDocFechaComparendo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(txtNumComparendo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel34)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel30)
                        .addComponent(cbPaisComparendo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel35)
                        .addComponent(txtHoraComparendo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel37)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(cbDeparComparendo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel39)
                            .addComponent(txtLicenciaConComparendo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMunicipioComparendo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(18, 18, 18)
                .addComponent(btnRegistrarComparendo)
                .addContainerGap(480, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(309, 309, 309)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(297, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("Comparendo", jPanel4);

        jLabel38.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel38.setText("Filtrar por:");

        tblFiltrarVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tblFiltrarVehiculos);

        bFiltrarVehiculo.setFont(new java.awt.Font("News706 BT", 0, 18)); // NOI18N
        bFiltrarVehiculo.setText("Filtrar");
        bFiltrarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFiltrarVehiculoActionPerformed(evt);
            }
        });

        bFiltrarVehiculoTodo.setFont(new java.awt.Font("News706 BT", 0, 18)); // NOI18N
        bFiltrarVehiculoTodo.setText("Listar Todo");
        bFiltrarVehiculoTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFiltrarVehiculoTodoActionPerformed(evt);
            }
        });

        cbConsultasVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Filtro", "Placa", "Clase", "Color", "Tipo de combustible", "Modelo", "Estado" }));
        cbConsultasVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbConsultasVehiculoActionPerformed(evt);
            }
        });

        tfFiltroVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFiltroVehiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel38)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfFiltroVehiculo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbConsultasVehiculo, 0, 170, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bFiltrarVehiculo)
                        .addGap(53, 53, 53)))
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bFiltrarVehiculoTodo)
                .addGap(408, 408, 408))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38)
                            .addComponent(cbConsultasVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfFiltroVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bFiltrarVehiculo))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bFiltrarVehiculoTodo)
                .addContainerGap(470, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1170, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 806, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Vehiculos", jPanel8);

        tblFiltrarLicencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(tblFiltrarLicencia);

        bFiltraLicenciaTodos.setFont(new java.awt.Font("News706 BT", 0, 18)); // NOI18N
        bFiltraLicenciaTodos.setText("Listar Todo");
        bFiltraLicenciaTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFiltraLicenciaTodosActionPerformed(evt);
            }
        });

        bFiltrarLicencia.setFont(new java.awt.Font("News706 BT", 0, 18)); // NOI18N
        bFiltrarLicencia.setText("Filtrar");
        bFiltrarLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFiltrarLicenciaActionPerformed(evt);
            }
        });

        tfFiltroLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFiltroLicenciaActionPerformed(evt);
            }
        });

        cbConsultasLicencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Filtro", "Número de licencia", "Fecha de expedición" }));
        cbConsultasLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbConsultasLicenciaActionPerformed(evt);
            }
        });

        jLabel42.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel42.setText("Filtrar por:");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bFiltraLicenciaTodos)
                .addGap(408, 408, 408))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bFiltrarLicencia)
                        .addGap(55, 55, 55))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel42)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ChooserDocLic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfFiltroLicencia, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbConsultasLicencia, 0, 170, Short.MAX_VALUE))
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel42)
                            .addComponent(cbConsultasLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ChooserDocLic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(tfFiltroLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bFiltrarLicencia))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bFiltraLicenciaTodos)
                .addContainerGap(470, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1170, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 806, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Licencia", jPanel9);

        bFiltraComparendosTodos.setFont(new java.awt.Font("News706 BT", 0, 18)); // NOI18N
        bFiltraComparendosTodos.setText("Listar Todo");
        bFiltraComparendosTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFiltraComparendosTodosActionPerformed(evt);
            }
        });

        bFiltrarComparendo.setFont(new java.awt.Font("News706 BT", 0, 18)); // NOI18N
        bFiltrarComparendo.setText("Filtrar");
        bFiltrarComparendo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFiltrarComparendoActionPerformed(evt);
            }
        });

        tfFiltroComparendo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFiltroComparendoActionPerformed(evt);
            }
        });

        cbConsultasComparendo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Filtro", "Municipio", "Fecha", "Número de licencia" }));
        cbConsultasComparendo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbConsultasComparendoActionPerformed(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel43.setText("Filtrar por:");

        tblFiltrarComparendo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(tblFiltrarComparendo);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bFiltraComparendosTodos)
                .addGap(408, 408, 408))
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel43)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfFiltroComparendo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbConsultasComparendo, 0, 170, Short.MAX_VALUE)))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bFiltrarComparendo)
                        .addGap(53, 53, 53)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel43)
                            .addComponent(cbConsultasComparendo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfFiltroComparendo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bFiltrarComparendo)
                        .addGap(189, 189, 189))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(bFiltraComparendosTodos)
                .addContainerGap(470, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1170, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 806, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Comparendo", jPanel10);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 982, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 188, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 377, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Consultas", jPanel7);

        jLabel24.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel24.setText("CONSECIONARIO");

        btnCerrarSession.setText("Cerrar Session");
        btnCerrarSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSessionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addGap(229, 229, 229)
                .addComponent(btnCerrarSession, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jTabbedPane2)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ChooserDocExpLic2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(btnCerrarSession))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 834, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ChooserDocExpLic2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String fech = variableFecha.format(ChooserDocMatricula.getDate());

        String tipo_servici = (String) cbTipoServicio.getSelectedItem();
        TipoServicio ts = conDAO.consultaTS(tipo_servici, "tipo_servicio");
        String clase_vehicul = (String) cbClase.getSelectedItem();
        ClaseVehiculo cv = conDAO.consultaCV(clase_vehicul, "clase_vehiculo");
        String estado_vehicul = (String) cbEstado.getSelectedItem();
        EstadoV ev = conDAO.consultaEV(estado_vehicul, "estado_vehiculo");
        String modelo_i = (String) cbModelo.getSelectedItem();
        ModeloVehiculo mv = conDAO.consultaMV(modelo_i, "modelo");
        String color_i = (String) cbColor.getSelectedItem();
        Color co = conDAO.consultaCO(color_i, "color");
        String tipo_combustible_i = (String) cbTipoCombustible.getSelectedItem();
        TipoCombustible tc = conDAO.consultaTC(tipo_combustible_i, "tipo_combustible");
        String propietario_i = txtPropietario.getText();
        if (ctlPro.SolicitudGuardar(0, propietario_i)) {

            Propieatario pro = conDAO.consultaPropietario(propietario_i);

            String placa = txtPlaca.getText();
            String licencia_transito = txtLicenciaT.getText();
            int tipo_servicio = ts.getId();
            int clase_vehiculo = cv.getId();
            int estado_vehiculo = ev.getId();
            int modelo_id = mv.getId();
            int color_id = co.getId();
            String numero_chasis = txtNumeroChasis.getText();
            String cilindrage = txtCilindraje.getText();
            int tipo_combustible_id = tc.getId();
            String[] fecha_ma = fech.split("/");
            String fecha_matricula = fecha_ma[2] + "-" + fecha_ma[1] + "-" + fecha_ma[0];
            String num_pasajeros = txtNumeroPasajeros.getText();
            int numero_poliza = Integer.parseInt(cbNumeroPoliza.getSelectedItem() + "");
            int propietario_id = pro.getId();

            if (ctlVehiculo.SolicitudGuardar(placa, licencia_transito, tipo_servicio, clase_vehiculo, estado_vehiculo, modelo_id, color_id, numero_chasis, cilindrage, tipo_combustible_id, fecha_matricula, num_pasajeros, numero_poliza, propietario_id)) {
                JOptionPane.showMessageDialog(null, "Vehiculo registrado exitosamente");
                listarVehiculos();

            }

        } else {
            JOptionPane.showMessageDialog(null, "Ciudadano no registrado");
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMarcaActionPerformed
        String marca = (String) cbMarca.getSelectedItem();
        Marca mc = conDAO.consultaMarca(marca);
        int idMarca = mc.getId();
        conDAO.listarEnComboGenericoConsul(cbModelo, "modelo", "marca", idMarca);
    }//GEN-LAST:event_cbMarcaActionPerformed

    private void txtRestriccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRestriccionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRestriccionesActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String fech3 = variableFecha2.format(ChooserDocExpLic.getDate());
        String[] fecha_ex = fech3.split("/");

        String num_licencia_cond = txtNumeroLicencia.getText();
        String fecha_expedicion = fecha_ex[2] + "-" + fecha_ex[1] + "-" + fecha_ex[0];
        String restriccion_conductor = txtRestricciones.getText();
        String organismo_expedidor = txtOrganismoEx.getText();
        String numero_identidad_ciudadano = txtNumeroCiudadano.getText();
        String categoria = (String) cbCategoria.getSelectedItem();

        if (ctlLicencia.SolicitudGuardar(num_licencia_cond, fecha_expedicion, restriccion_conductor, organismo_expedidor, numero_identidad_ciudadano)) {
            if (ctlCategoria.SolicitudGuardar(0, num_licencia_cond, categoria)) {
                JOptionPane.showMessageDialog(null, "La licencia de conduccion del ciudadano con identificacion: " + numero_identidad_ciudadano + " Fue guardada con exito");
            }

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtCedulaTraspasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaTraspasoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaTraspasoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String placa = txtVehiculoTraspaso.getText();
        String cedula = txtCedulaTraspaso.getText();
        Propieatario pro = conDAO.consultaPropietario(cedula);
        int ced = pro.getId();

        boolean datos1 = ctlPro.SolicitudBuscar3(ced);

        if (datos1 == true) {
            if (ctlVehiculo.SolicitudModificar(placa, ced)) {
                JOptionPane.showMessageDialog(null, "El traspaso del vehiculo con placa: " + placa + " al ciudadano con identificacion: " + cedula);
            }
            //Propieatario pro = conDAO.consultaPropietario(cedula);
            // int ced = pro.getId();

        } else {
            if (ctlPro.SolicitudGuardar(0, cedula)) {
                System.out.println("entro");
                Propieatario pro1 = conDAO.consultaPropietario(cedula);
                int ced2 = pro1.getId();
                if (ctlVehiculo.SolicitudModificar(placa, ced2)) {
                    JOptionPane.showMessageDialog(null, "El traspaso del vehiculo con placa: " + placa + " al ciudadano con identificacion: " + cedula);

                }
            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnCerrarSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSessionActionPerformed
        new FrmInicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSessionActionPerformed

    private void cbPaisComparendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPaisComparendoActionPerformed
        try {
            String nombre_pais = (String) cbPaisComparendo.getSelectedItem();
            Pais pais = daoAse.consultaPais(nombre_pais);
            int idPais = pais.getId();

            daoAse.listarEnComboDepartamentosCon(idPais);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al listar departamentos");
        }

    }//GEN-LAST:event_cbPaisComparendoActionPerformed

    private void cbDeparComparendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDeparComparendoActionPerformed
        try {
            String nombre_depar = (String) cbDeparComparendo.getSelectedItem();
            Departamento depar = daoAse.consultaDepar(nombre_depar);
            int idDepar = depar.getId();

            daoAse.listarEnComboMunicipiosCon(idDepar);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al listar municipios");
        }
    }//GEN-LAST:event_cbDeparComparendoActionPerformed

    private void btnRegistrarComparendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarComparendoActionPerformed
        String fech = variableFecha.format(ChooserDocMatricula.getDate());
         String[] fecha_ma = fech.split("/");
            
        

        int numComparendo = Integer.parseInt(txtNumComparendo.getText());
        String tipoInfr = (String) cbTipoInfraccion.getSelectedItem();
        TipoInfraccion tipoInfracci = ctlComp.consultaTipoInfrac(tipoInfr);
        int tipoInfraccion = tipoInfracci.getId();
        String muni = (String) cbMunicipioComparendo.getSelectedItem();
        Municipio municipi = ctlComp.consultaMuni(muni);
        int municipio = municipi.getId();
        String fecha = fecha_ma[2] + "-" + fecha_ma[1] + "-" + fecha_ma[0];
        String Hora = txtHoraComparendo.getText();
        String fechaHora = fecha + " a las " + Hora;
        int licenciaConduccion = Integer.parseInt(txtLicenciaConComparendo.getText());

        if (ctlComp.SolicitudGuardar(numComparendo, tipoInfraccion, municipio, fechaHora, licenciaConduccion)) {
            JOptionPane.showMessageDialog(null, "El comparendo Numero:  " + numComparendo + "    fue guardada con exito");
            limpiarComparendo();
            listarComparendo();
        } else {
            JOptionPane.showMessageDialog(null, "Error al intentar guaradar el comparendo");
            limpiarComparendo();
        }

    }//GEN-LAST:event_btnRegistrarComparendoActionPerformed

    private void btnAsignarCuiComparendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarCuiComparendoActionPerformed
        int numComparendo = Integer.parseInt(txtNumComparendo.getText());
        String cedulaCiud = txtCedulaCiuComp.getText();

        if (ctlCompUs.SolicitudGuardar(0, cedulaCiud, numComparendo)) {
            JOptionPane.showMessageDialog(null, "El comparendo Numero: " + numComparendo + " Fue asignado a el usuario con cedula: " + cedulaCiud);
            limpiarComparendo();
        } else {
            JOptionPane.showMessageDialog(null, "Error al asignar el comparendo");
        }

    }//GEN-LAST:event_btnAsignarCuiComparendoActionPerformed

    private void cbMunicipioComparendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMunicipioComparendoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMunicipioComparendoActionPerformed


    private void bFiltrarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFiltrarVehiculoActionPerformed
       String filtro = tfFiltroVehiculo.getText();
        int combo= cbConsultasVehiculo.getSelectedIndex();

        if (combo==1){
            tblFiltrarVehiculos.setModel(ctlVehiculo.solicitudListarVehiPlaca(filtro));
        }else if(combo==2){
            tblFiltrarVehiculos.setModel(ctlVehiculo.solicitudListarVehiClase(filtro));
        }else if(combo==3){
            tblFiltrarVehiculos.setModel(ctlVehiculo.solicitudListarVehiColor(filtro));
        }else if(combo==3){
            tblFiltrarVehiculos.setModel(ctlVehiculo.solicitudListarVehitipoCombus(filtro));
        }else if(combo==3){
            tblFiltrarVehiculos.setModel(ctlVehiculo.solicitudListarVehiModelo(filtro));
        }else if(combo==3){
            tblFiltrarVehiculos.setModel(ctlVehiculo.solicitudListarVehiEstado(filtro));
        }else{
            JOptionPane.showMessageDialog(null, "Ingrese dato a filtrar");
        }
    }//GEN-LAST:event_bFiltrarVehiculoActionPerformed

    private void bFiltrarVehiculoTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFiltrarVehiculoTodoActionPerformed
       listarVehiculos();
    }//GEN-LAST:event_bFiltrarVehiculoTodoActionPerformed

    private void cbConsultasVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbConsultasVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbConsultasVehiculoActionPerformed

    private void tfFiltroVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFiltroVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFiltroVehiculoActionPerformed

    private void bFiltraLicenciaTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFiltraLicenciaTodosActionPerformed
       listarLicencias();
    }//GEN-LAST:event_bFiltraLicenciaTodosActionPerformed

    private void bFiltrarLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFiltrarLicenciaActionPerformed
       String filtro = tfFiltroLicencia.getText();
        int combo= cbConsultasLicencia.getSelectedIndex();

        if (combo==1){
            tblFiltrarLicencia.setModel(ctlLicencia.SolicitudListarLicenciasCed(filtro));
        }else if(combo==2){
            tblFiltrarLicencia.setModel(ctlLicencia.SolicitudListarLicenciasFecha(filtro));
        }else{
            JOptionPane.showMessageDialog(null, "Ingrese dato a filtrar");
        }
    }//GEN-LAST:event_bFiltrarLicenciaActionPerformed

    private void tfFiltroLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFiltroLicenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFiltroLicenciaActionPerformed

    private void cbConsultasLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbConsultasLicenciaActionPerformed
if(cbConsultasLicencia.getSelectedIndex() == 1){
     ChooserDocLic.setEnabled(false);
     tfFiltroLicencia.setEnabled(true);
}else if
    (cbConsultasLicencia.getSelectedIndex() == 2){
    ChooserDocLic.setEnabled(true);
    tfFiltroLicencia.setEnabled(false);
}
    
    }//GEN-LAST:event_cbConsultasLicenciaActionPerformed

    private void bFiltraComparendosTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFiltraComparendosTodosActionPerformed
       listarComparendo();
    }//GEN-LAST:event_bFiltraComparendosTodosActionPerformed

    private void bFiltrarComparendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFiltrarComparendoActionPerformed
      String filtro = tfFiltroComparendo.getText();
        int combo= cbConsultasComparendo.getSelectedIndex();

        if (combo==1){
            tblFiltrarComparendo.setModel(ctlComp.solicitudListarCompMun(filtro));
        }else if(combo==2){
            tblFiltrarComparendo.setModel(ctlComp.solicitudListarComparendoFecha(filtro));
        }else if(combo==3){
            tblFiltrarComparendo.setModel(ctlComp.solicitudListarComparendoNumLic(filtro));
        }else{
            JOptionPane.showMessageDialog(null, "Ingrese dato a filtrar");
        }      
    }//GEN-LAST:event_bFiltrarComparendoActionPerformed

    private void tfFiltroComparendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFiltroComparendoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFiltroComparendoActionPerformed

    private void cbConsultasComparendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbConsultasComparendoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbConsultasComparendoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
ctlReporte.generarReporte();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser ChooserDocExpLic;
    private com.toedter.calendar.JDateChooser ChooserDocExpLic2;
    private com.toedter.calendar.JDateChooser ChooserDocFechaComparendo;
    private com.toedter.calendar.JDateChooser ChooserDocLic;
    private com.toedter.calendar.JDateChooser ChooserDocMatricula;
    private javax.swing.JButton bFiltraComparendosTodos;
    private javax.swing.JButton bFiltraLicenciaTodos;
    private javax.swing.JButton bFiltrarComparendo;
    private javax.swing.JButton bFiltrarLicencia;
    private javax.swing.JButton bFiltrarVehiculo;
    private javax.swing.JButton bFiltrarVehiculoTodo;
    private javax.swing.JButton btnAsignarCuiComparendo;
    private javax.swing.JButton btnCerrarSession;
    private javax.swing.JButton btnRegistrarComparendo;
    private javax.swing.JComboBox<String> cbCategoria;
    private javax.swing.JComboBox<String> cbClase;
    private javax.swing.JComboBox<String> cbColor;
    private javax.swing.JComboBox<String> cbConsultasComparendo;
    private javax.swing.JComboBox<String> cbConsultasLicencia;
    private javax.swing.JComboBox<String> cbConsultasVehiculo;
    public static javax.swing.JComboBox<String> cbDeparComparendo;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JComboBox<String> cbMarca;
    private javax.swing.JComboBox<String> cbModelo;
    public static javax.swing.JComboBox<String> cbMunicipioComparendo;
    private javax.swing.JComboBox<String> cbNumeroPoliza;
    public static javax.swing.JComboBox<String> cbPaisComparendo;
    private javax.swing.JComboBox<String> cbTipoCombustible;
    public static javax.swing.JComboBox<String> cbTipoInfraccion;
    private javax.swing.JComboBox<String> cbTipoServicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable tblComparendoConse;
    private javax.swing.JTable tblFiltrarComparendo;
    private javax.swing.JTable tblFiltrarLicencia;
    private javax.swing.JTable tblFiltrarVehiculos;
    private javax.swing.JTable tblLicenciaConse;
    private javax.swing.JTable tblVehiculoConse;
    private javax.swing.JTextField tfFiltroComparendo;
    private javax.swing.JTextField tfFiltroLicencia;
    private javax.swing.JTextField tfFiltroVehiculo;
    private javax.swing.JTextField txtCedulaCiuComp;
    private javax.swing.JTextField txtCedulaTraspaso;
    private javax.swing.JTextField txtCilindraje;
    private javax.swing.JTextField txtHoraComparendo;
    private javax.swing.JTextField txtLicenciaConComparendo;
    private javax.swing.JTextField txtLicenciaT;
    private javax.swing.JTextField txtNumComparendo;
    private javax.swing.JTextField txtNumeroChasis;
    private javax.swing.JTextField txtNumeroCiudadano;
    private javax.swing.JTextField txtNumeroLicencia;
    private javax.swing.JTextField txtNumeroPasajeros;
    private javax.swing.JTextField txtOrganismoEx;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtPropietario;
    private javax.swing.JTextField txtRestricciones;
    private javax.swing.JTextField txtVehiculoTraspaso;
    // End of variables declaration//GEN-END:variables

    //metodos para listar tabla
    private void listarComparendo() {
        tblComparendoConse.setModel(ctlComp.solicitudListar());
        tblFiltrarComparendo.setModel(ctlComp.solicitudListar());
    }

    private void listarVehiculos() {
        tblVehiculoConse.setModel(ctlVehiculo.solicitudListarAll());
        tblFiltrarVehiculos.setModel(ctlVehiculo.solicitudListarAll());
    }

    private void listarLicencias() {
        tblLicenciaConse.setModel(ctlLicencia.SolicitudListar());
        tblFiltrarLicencia.setModel(ctlLicencia.SolicitudListar());
    }

    //metodos para limpiar Campos
    private void limpiarComparendo() {
        txtCedulaCiuComp.setText("");
        txtLicenciaConComparendo.setText("");
        txtCedulaCiuComp.setText("");
        ChooserDocFechaComparendo.setCalendar(null);
        txtHoraComparendo.setText("");
    }
    
 
    
}
